[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "learning_notebook"
version = "0.1.0"
dependencies = [
  "jupyter",
  "scikit-learn",
  "numpy",
  "pandas",
]
requires-python = ">= 3.12"
authors = [
  {name = "lazy_skunk"}
]
maintainers = [
  {name = "lazy_skunk"}
]
description = "learning_notebook"
readme = "README.md"
license = {file = "LICENSE.txt"}

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
  "isort",
  "mypy",
]

[tool.black]
line-length = 79

# Flake8 cannot be configured via pyproject.toml
# [tool.flake8]
# max-line-length = 79

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true